CREATE PROCEDURE ALTERACONTAS(
  PCODIGO INTEGER,
  PCODIGOTIPOCONTA INTEGER,
  PCODIGOAREA INTEGER,
  PDESCRICAO VARCHAR(150) CHARACTER SET ISO8859_1,
  PEMAIL VARCHAR(40) CHARACTER SET ISO8859_1,
  PNUMERO VARCHAR(10) CHARACTER SET ISO8859_1,
  PATIVO CHAR(1) CHARACTER SET ISO8859_1)
AS
BEGIN
  IF (NOT EXISTS(SELECT CODIGO FROM CONTAS
  WHERE CODIGOTIPOCONTA = :PCODIGOTIPOCONTA AND DESCRICAO = :PDESCRICAO
  AND CODIGOAREA = :PCODIGOAREA AND CODIGO <> :PCODIGO)) THEN
  BEGIN
    UPDATE CONTAS
    SET CODIGOTIPOCONTA = :PCODIGOTIPOCONTA, CODIGOAREA = :PCODIGOAREA,
    DESCRICAO = :PDESCRICAO, EMAIL = :PEMAIL, NUMERO = :PNUMERO, ATIVO = :PATIVO
    WHERE CODIGO = :PCODIGO;
    SUSPEND;
  END
  ELSE
    EXCEPTION REGISTROJAEXISTE;
END
