CREATE PROCEDURE ALTERAAREAS(
  PCODIGO INTEGER,
  PNOME VARCHAR(40) CHARACTER SET ISO8859_1)
AS
BEGIN
  IF (NOT EXISTS(SELECT CODIGO FROM AREAS WHERE NOME = :PNOME
  AND CODIGO <> :PCODIGO)) THEN
  BEGIN
    UPDATE AREAS
    SET NOME = :PNOME
    WHERE CODIGO = :PCODIGO;
    SUSPEND;
  END
  ELSE
    EXCEPTION REGISTROJAEXISTE;
END
