CREATE PROCEDURE ALTERALANCAMENTOS(
  PCODIGO INTEGER,
  PCODIGOCONTA INTEGER,
  PGRUPO CHAR(6) CHARACTER SET ISO8859_1,
  PRECEITA CHAR(1) CHARACTER SET ISO8859_1,
  PDATA DATE,
  PNEMPENHO INTEGER,
  PDESCRICAO VARCHAR(150) CHARACTER SET ISO8859_1,
  PDEBITO NUMERIC(18, 2),
  PCREDITO NUMERIC(18, 2),
  POBSERVACAO VARCHAR(150) CHARACTER SET ISO8859_1)
AS
BEGIN
  IF (PDEBITO <> 0) THEN
  BEGIN
    UPDATE LANCAMENTOS
    SET CODIGOCONTA = :PCODIGOCONTA,
    GRUPO = :PGRUPO, RECEITA = :PRECEITA, DATA = :PDATA, NEMPENHO = :PNEMPENHO,
    DESCRICAO = :PDESCRICAO, DEBITO = :PDEBITO, CREDITO = NULL,
    OBSERVACAO = :POBSERVACAO
    WHERE CODIGO = :PCODIGO;
    SUSPEND;
  END
  ELSE
  BEGIN
    UPDATE LANCAMENTOS
    SET CODIGOCONTA = :PCODIGOCONTA,
    GRUPO = :PGRUPO, RECEITA = :PRECEITA, DATA = :PDATA, NEMPENHO = :PNEMPENHO,
    DESCRICAO = :PDESCRICAO, DEBITO = NULL, CREDITO = :PCREDITO,
    OBSERVACAO = :POBSERVACAO
    WHERE CODIGO = :PCODIGO;
    SUSPEND;
  END
END
