CREATE PROCEDURE ALTERADOTACAO(
  PCODIGO INTEGER,
  PDOTACAO VARCHAR(40) CHARACTER SET ISO8859_1,
  PGRUPO CHAR(6) CHARACTER SET ISO8859_1,
  PDESCRICAOGRUPO VARCHAR(150) CHARACTER SET ISO8859_1,
  PITEM CHAR(6) CHARACTER SET ISO8859_1,
  PRECEITA CHAR(1) CHARACTER SET ISO8859_1,
  PDESCRICAOITEM VARCHAR(150) CHARACTER SET ISO8859_1)
AS
BEGIN
  IF (NOT EXISTS(SELECT CODIGO FROM DOTACAO WHERE DOTACAO = :PDOTACAO
  AND CODIGO <> :PCODIGO)) THEN
  BEGIN
    UPDATE DOTACAO
    SET DOTACAO = :PDOTACAO, GRUPO = :PGRUPO,
    DESCRICAOGRUPO = :PDESCRICAOGRUPO, ITEM = :PITEM, RECEITA = :PRECEITA,
    DESCRICAOITEM = :PDESCRICAOITEM
    WHERE CODIGO = :PCODIGO;
    SUSPEND;
  END
  ELSE
    EXCEPTION REGISTROJAEXISTE;
END
