CREATE PROCEDURE ALTERAFICHAORCAMENTARIA(
  PCODIGO INTEGER,
  PCODIGODOTACAO INTEGER,
  PDATA DATE,
  PNEMPENHO INTEGER,
  PDESCRICAO VARCHAR(150) CHARACTER SET ISO8859_1,
  PDEBITO NUMERIC(18, 2),
  PCREDITO NUMERIC(18, 2),
  POBSERVACAO VARCHAR(150) CHARACTER SET ISO8859_1)
AS
BEGIN
  IF (PDEBITO <> 0) THEN
  BEGIN
    UPDATE FICHAORCAMENTARIA
    SET CODIGODOTACAO = :PCODIGODOTACAO,
    DATA = :PDATA, NEMPENHO = :PNEMPENHO, DESCRICAO = :PDESCRICAO,
    DEBITO = :PDEBITO, CREDITO = NULL, OBSERVACAO = :POBSERVACAO
    WHERE CODIGO = :PCODIGO;
    UPDATE LANCAMENTOS
    SET DATA = :PDATA,
    NEMPENHO = :PNEMPENHO, DESCRICAO = :PDESCRICAO, DEBITO = :PDEBITO,
    CREDITO = NULL, OBSERVACAO = :POBSERVACAO
    WHERE CODIGOORCAMENTO = :PCODIGO;
    SUSPEND;
  END
  ELSE
  BEGIN
    UPDATE FICHAORCAMENTARIA
    SET CODIGODOTACAO = :PCODIGODOTACAO,
    DATA = :PDATA, NEMPENHO = :PNEMPENHO, DESCRICAO = :PDESCRICAO,
    DEBITO = NULL, CREDITO = :PCREDITO, OBSERVACAO = :POBSERVACAO
    WHERE CODIGO = :PCODIGO;
    UPDATE LANCAMENTOS
    SET DATA = :PDATA,
    NEMPENHO = :PNEMPENHO, DESCRICAO = :PDESCRICAO, DEBITO = NULL,
    CREDITO = :PCREDITO, OBSERVACAO = :POBSERVACAO
    WHERE CODIGOORCAMENTO = :PCODIGO;
    SUSPEND;
  END
END
