CREATE PROCEDURE ALTERATIPOSCONTAS(
  PCODIGO INTEGER,
  PDESCRICAO VARCHAR(150) CHARACTER SET ISO8859_1,
  PFICHAORCAMENTARIA CHAR(1) CHARACTER SET ISO8859_1,
  PBALANCETE CHAR(1) CHARACTER SET ISO8859_1)
AS
BEGIN
  IF (NOT EXISTS(SELECT CODIGO FROM TIPOSCONTAS WHERE DESCRICAO = :PDESCRICAO
  AND CODIGO <> :PCODIGO)) THEN
  BEGIN
    UPDATE TIPOSCONTAS
    SET DESCRICAO = :PDESCRICAO, FICHAORCAMENTARIA = :PFICHAORCAMENTARIA,
    BALANCETE = :PBALANCETE
    WHERE CODIGO = :PCODIGO;
    SUSPEND;
  END
  ELSE
    EXCEPTION REGISTROJAEXISTE;
END
