CREATE PROCEDURE ALTERACONTASUSUARIOS(
  PCODIGO INTEGER,
  PCODIGOCONTA INTEGER,
  PCODIGOUSUARIO INTEGER)
AS
BEGIN
  UPDATE CONTASUSUARIOS
  SET CODIGOCONTA = :PCODIGOCONTA, CODIGOUSUARIO = :PCODIGOUSUARIO
  WHERE CODIGO = :PCODIGO;
  SUSPEND;
END
