CREATE PROCEDURE INSERETIPOSCONTAS(
  PDESCRICAO VARCHAR(150) CHARACTER SET ISO8859_1,
  PFICHAORCAMENTARIA CHAR(1) CHARACTER SET ISO8859_1,
  PBALANCETE CHAR(1) CHARACTER SET ISO8859_1)
AS
BEGIN
  INSERT INTO TIPOSCONTAS (DESCRICAO, FICHAORCAMENTARIA, BALANCETE)
  VALUES (:PDESCRICAO, :PFICHAORCAMENTARIA, :PBALANCETE);
  SUSPEND;
END
