CREATE PROCEDURE INSERESALDOAREAS(
  PCODIGOMOVIMENTO INTEGER,
  PCODIGOAREA INTEGER,
  PSALDOCONSUMO NUMERIC(18, 2))
AS
BEGIN
  INSERT INTO SALDOAREAS (CODIGOMOVIMENTO, CODIGOAREA, SALDOCONSUMO)
  VALUES (:PCODIGOMOVIMENTO, :PCODIGOAREA, :PSALDOCONSUMO);
  SUSPEND;
END
