CREATE PROCEDURE INSEREUSUARIOS(
  PLOGIN VARCHAR(20) CHARACTER SET ISO8859_1,
  PSENHA CHAR(10) CHARACTER SET ISO8859_1,
  PDESCRICAO VARCHAR(150) CHARACTER SET ISO8859_1)
AS
BEGIN
  INSERT INTO USUARIOS (LOGIN, SENHA, DESCRICAO)
  VALUES (:PLOGIN, :PSENHA, :PDESCRICAO);
  SUSPEND;
END
