CREATE PROCEDURE INSERECONTASUSUARIOS(
  PCODIGOCONTA INTEGER,
  PCODIGOUSUARIO INTEGER)
AS
BEGIN
  INSERT INTO CONTASUSUARIOS (CODIGOCONTA, CODIGOUSUARIO)
  VALUES (:PCODIGOCONTA, :PCODIGOUSUARIO);
  SUSPEND;
END
