CREATE PROCEDURE INSEREMOVIMENTO(
  PANO INTEGER,
  PCONCLUIDO CHAR(1) CHARACTER SET ISO8859_1,
  PATIVO CHAR(1) CHARACTER SET ISO8859_1)
AS
BEGIN
  IF (PATIVO = 'S') THEN
  BEGIN
    UPDATE MOVIMENTO
    SET ATIVO = '';
    INSERT INTO MOVIMENTO (ANO, CONCLUIDO, ATIVO)
    VALUES (:PANO, :PCONCLUIDO, :PATIVO);
    SUSPEND;
  END
  ELSE
  BEGIN
    INSERT INTO MOVIMENTO (ANO, CONCLUIDO, ATIVO)
    VALUES (:PANO, :PCONCLUIDO, :PATIVO);
    SUSPEND;
  END
END
