CREATE PROCEDURE INSERELANCAMENTOS(
  PCODIGOMOVIMENTO INTEGER,
  PCODIGOORCAMENTO INTEGER,
  PCODIGOCONTA INTEGER,
  PGRUPO CHAR(6) CHARACTER SET ISO8859_1,
  PRECEITA CHAR(1) CHARACTER SET ISO8859_1,
  PDATA DATE,
  PNEMPENHO INTEGER,
  PDESCRICAO VARCHAR(150) CHARACTER SET ISO8859_1,
  PDEBITO NUMERIC(18, 2),
  PCREDITO NUMERIC(18, 2),
  POBSERVACAO VARCHAR(150) CHARACTER SET ISO8859_1)
AS
BEGIN
  IF (PDEBITO <> 0) THEN
  BEGIN
    INSERT INTO LANCAMENTOS (CODIGOMOVIMENTO, CODIGOORCAMENTO, CODIGOCONTA,
    GRUPO, RECEITA, DATA, NEMPENHO, DESCRICAO, DEBITO, OBSERVACAO)
    VALUES (:PCODIGOMOVIMENTO, :PCODIGOORCAMENTO, :PCODIGOCONTA, :PGRUPO,
    :PRECEITA, :PDATA, :PNEMPENHO, :PDESCRICAO, :PDEBITO, :POBSERVACAO);
    SUSPEND;
  END
  ELSE
  BEGIN
    INSERT INTO LANCAMENTOS (CODIGOMOVIMENTO, CODIGOORCAMENTO, CODIGOCONTA,
    GRUPO, RECEITA, DATA, NEMPENHO, DESCRICAO, CREDITO, OBSERVACAO)
    VALUES (:PCODIGOMOVIMENTO, :PCODIGOORCAMENTO, :PCODIGOCONTA, :PGRUPO,
    :PRECEITA, :PDATA, :PNEMPENHO, :PDESCRICAO, :PCREDITO, :POBSERVACAO);
    SUSPEND;
  END
END
