CREATE PROCEDURE INSEREDOTACAO(
  PDOTACAO VARCHAR(40) CHARACTER SET ISO8859_1,
  PGRUPO CHAR(6) CHARACTER SET ISO8859_1,
  PDESCRICAOGRUPO VARCHAR(150) CHARACTER SET ISO8859_1,
  PITEM CHAR(6) CHARACTER SET ISO8859_1,
  PRECEITA CHAR(1) CHARACTER SET ISO8859_1,
  PDESCRICAOITEM VARCHAR(150) CHARACTER SET ISO8859_1)
AS
BEGIN
  INSERT INTO DOTACAO (DOTACAO, GRUPO, DESCRICAOGRUPO, ITEM, RECEITA,
  DESCRICAOITEM)
  VALUES (:PDOTACAO, :PGRUPO, :PDESCRICAOGRUPO, :PITEM, :PRECEITA,
  :PDESCRICAOITEM);
  SUSPEND;
END
