CREATE PROCEDURE OBTEMTODOSMOVIMENTOS
RETURNS(
  RCODIGO INTEGER,
  RANO INTEGER,
  RCONCLUIDO CHAR(1) CHARACTER SET ISO8859_1,
  RATIVO CHAR(1) CHARACTER SET ISO8859_1,
  RUSUARIO CHAR(10) CHARACTER SET ISO8859_1,
  RDHMODIFICACAO TIMESTAMP)
AS
BEGIN
  FOR SELECT CODIGO, ANO, CONCLUIDO, ATIVO, USUARIO, DHMODIFICACAO
  FROM MOVIMENTO
  INTO :RCODIGO, :RANO, :RCONCLUIDO, :RATIVO, :RUSUARIO, :RDHMODIFICACAO
  DO
  SUSPEND;
END
