CREATE PROCEDURE OBTEMSALDOAREAS(
  PCODIGOAREA INTEGER,
  PCODIGOMOVIMENTO INTEGER)
RETURNS(
  RCODIGO INTEGER,
  RNOME VARCHAR(40) CHARACTER SET ISO8859_1,
  RUSUARIO CHAR(10) CHARACTER SET ISO8859_1,
  RDHMODIFICACAO TIMESTAMP,
  RSALDOCONSUMO NUMERIC(18, 2))
AS
BEGIN
  FOR SELECT SA.CODIGO, A.NOME, SA.SALDOCONSUMO, SA.USUARIO, SA.DHMODIFICACAO
  FROM SALDOAREAS SA
  INNER JOIN AREAS A ON (SA.CODIGOAREA = A.CODIGO)
  WHERE SA.CODIGOAREA = :PCODIGOAREA AND SA.CODIGOMOVIMENTO = :PCODIGOMOVIMENTO
  INTO :RCODIGO, :RNOME, :RSALDOCONSUMO, :RUSUARIO, :RDHMODIFICACAO
  DO
  SUSPEND;
END
