CREATE PROCEDURE OBTEMAREAS(
  PCODIGO INTEGER)
RETURNS(
  RCODIGO INTEGER,
  RNOME VARCHAR(40) CHARACTER SET ISO8859_1,
  RUSUARIO CHAR(10) CHARACTER SET ISO8859_1,
  RDHMODIFICACAO TIMESTAMP,
  RSALDOCONSUMO NUMERIC(18, 2))
AS
BEGIN
  FOR SELECT A.CODIGO, A.NOME, A.USUARIO, A.DHMODIFICACAO
  FROM AREAS A
  WHERE A.CODIGO = :PCODIGO
  INTO :RCODIGO, :RNOME, :RUSUARIO, :RDHMODIFICACAO
  DO
  SUSPEND;
END
