CREATE PROCEDURE OBTEMTODOSUNIDADE
RETURNS(
  RCODIGO INTEGER,
  RID CHAR(2) CHARACTER SET ISO8859_1,
  RNOME VARCHAR(70) CHARACTER SET ISO8859_1,
  RDEPARTAMENTO VARCHAR(80) CHARACTER SET ISO8859_1,
  RUSUARIO CHAR(10) CHARACTER SET ISO8859_1,
  RDHMODIFICACAO TIMESTAMP)
AS
BEGIN
  FOR SELECT CODIGO, ID, NOME, DEPARTAMENTO, USUARIO, DHMODIFICACAO
  FROM UNIDADE
  INTO :RCODIGO, :RID, :RNOME, :RDEPARTAMENTO, :RUSUARIO, :RDHMODIFICACAO
  DO
  SUSPEND;
END
