CREATE PROCEDURE OBTEMCONTASUSUARIOSCODIGO(
  PCODIGO INTEGER)
RETURNS(
  RCODIGO INTEGER,
  RCODIGOCONTA INTEGER,
  RCODIGOUSUARIO INTEGER,
  RUSUARIO CHAR(10) CHARACTER SET ISO8859_1,
  RDHMODIFICACAO TIMESTAMP,
  RLOGINUSUARIO VARCHAR(20) CHARACTER SET ISO8859_1,
  RDESCRICAOUSUARIO VARCHAR(150) CHARACTER SET ISO8859_1,
  RDESCRICAOCONTA VARCHAR(150) CHARACTER SET ISO8859_1,
  RDESCRICAOTIPOCONTA VARCHAR(150) CHARACTER SET ISO8859_1)
AS
BEGIN
  FOR SELECT C.CODIGO, C.CODIGOCONTA, C.CODIGOUSUARIO, C.USUARIO,
  C.DHMODIFICACAO, U.LOGIN, U.DESCRICAO, CT.DESCRICAO, TC.DESCRICAO
  FROM CONTASUSUARIOS C
  INNER JOIN USUARIOS    U  ON (C.CODIGOUSUARIO = U.CODIGO)
  INNER JOIN CONTAS      CT ON (C.CODIGOCONTA = CT.CODIGO)
  INNER JOIN TIPOSCONTAS TC ON (CT.CODIGOTIPOCONTA = TC.CODIGO)
  WHERE C.CODIGO = :PCODIGO
  ORDER BY TC.DESCRICAO, CT.DESCRICAO
  INTO :RCODIGO, :RCODIGOCONTA, :RCODIGOUSUARIO, :RUSUARIO, :RDHMODIFICACAO,
  :RLOGINUSUARIO, :RDESCRICAOUSUARIO, :RDESCRICAOCONTA, :RDESCRICAOTIPOCONTA
  DO
  SUSPEND;
END
