CREATE PROCEDURE OBTEMTODOSCONTASAREAS(
  PCODIGOAREA INTEGER)
RETURNS(
  RCODIGO INTEGER,
  RDESCRICAO VARCHAR(150) CHARACTER SET ISO8859_1,
  RNOMEAREA VARCHAR(40) CHARACTER SET ISO8859_1)
AS
BEGIN
  FOR SELECT C.CODIGO, C.DESCRICAO, A.NOME
  FROM CONTAS C
  LEFT JOIN AREAS A ON (C.CODIGOAREA = A.CODIGO)
  WHERE C.CODIGOAREA = :PCODIGOAREA
  INTO :RCODIGO, :RDESCRICAO, :RNOMEAREA
  DO
  SUSPEND;
END
