CREATE PROCEDURE OBTEMUSUARIOS(
  PCODIGO INTEGER)
RETURNS(
  RCODIGO INTEGER,
  RLOGIN VARCHAR(20) CHARACTER SET ISO8859_1,
  RSENHA VARCHAR(10) CHARACTER SET ISO8859_1,
  RDESCRICAO VARCHAR(150) CHARACTER SET ISO8859_1,
  RUSUARIO CHAR(10) CHARACTER SET ISO8859_1,
  RDHMODIFICACAO TIMESTAMP)
AS
BEGIN
  FOR SELECT CODIGO, LOGIN, SENHA, DESCRICAO, USUARIO, DHMODIFICACAO
  FROM USUARIOS
  WHERE CODIGO = :PCODIGO
  INTO :RCODIGO, :RLOGIN, :RSENHA, :RDESCRICAO, :RUSUARIO, :RDHMODIFICACAO
  DO
  SUSPEND;
END
