CREATE PROCEDURE OBTEMFICHAORCAMENTARIACODIGO(
  PCODIGO INTEGER)
RETURNS(
  RCODIGO INTEGER,
  RCODIGOMOVIMENTO INTEGER,
  RCODIGODOTACAO INTEGER,
  RDATA DATE,
  RNEMPENHO INTEGER,
  RDESCRICAO VARCHAR(150) CHARACTER SET ISO8859_1,
  RDEBITO NUMERIC(18, 2),
  RCREDITO NUMERIC(18, 2),
  RSALDO NUMERIC(18, 2),
  ROBSERVACAO VARCHAR(150) CHARACTER SET ISO8859_1,
  RDOTACAO VARCHAR(40) CHARACTER SET ISO8859_1,
  RDESCRICAOCONTA VARCHAR(150) CHARACTER SET ISO8859_1,
  RDESCRICAOTIPOCONTA VARCHAR(150) CHARACTER SET ISO8859_1)
AS
BEGIN
  FOR SELECT FO.CODIGO, FO.CODIGOMOVIMENTO, FO.CODIGODOTACAO, FO.DATA,
  FO.NEMPENHO, FO.DESCRICAO, FO.DEBITO, FO.CREDITO, FO.SALDO, FO.OBSERVACAO,
  D.DOTACAO, C.DESCRICAO, T.DESCRICAO
  FROM FICHAORCAMENTARIA FO
  INNER JOIN DOTACAO    D ON (FO.CODIGODOTACAO = D.CODIGO)
  LEFT JOIN LANCAMENTOS L ON (FO.CODIGO = L.CODIGOORCAMENTO)
  LEFT JOIN CONTAS      C ON (L.CODIGOCONTA = C.CODIGO)
  LEFT JOIN TIPOSCONTAS T ON (C.CODIGOTIPOCONTA = T.CODIGO)
  WHERE FO.CODIGO = :PCODIGO
  INTO :RCODIGO, :RCODIGOMOVIMENTO, :RCODIGODOTACAO, :RDATA, :RNEMPENHO,
  :RDESCRICAO, :RDEBITO, :RCREDITO, :RSALDO, :ROBSERVACAO,
  :RDOTACAO, :RDESCRICAOCONTA, :RDESCRICAOTIPOCONTA
  DO
  SUSPEND;
END
