CREATE PROCEDURE RELALANCAMENTOSFO(
  PCODIGODOTACAO INTEGER,
  PCODIGOMOVIMENTO INTEGER,
  PDATADE DATE,
  PDATAATE DATE)
RETURNS(
  RCODIGO INTEGER,
  RCODIGOMOVIMENTO INTEGER,
  RCODIGODOTACAO INTEGER,
  RGRUPO CHAR(6) CHARACTER SET ISO8859_1,
  RRECEITA CHAR(1) CHARACTER SET ISO8859_1,
  RDATA DATE,
  RNEMPENHO INTEGER,
  RDESCRICAO VARCHAR(150) CHARACTER SET ISO8859_1,
  RDEBITO NUMERIC(18, 2),
  RCREDITO NUMERIC(18, 2),
  RSALDO NUMERIC(18, 2),
  ROBSERVACAO VARCHAR(150) CHARACTER SET ISO8859_1,
  RDESCRICAODOTACAO VARCHAR(150) CHARACTER SET ISO8859_1)
AS
BEGIN
  FOR SELECT FO.CODIGO, FO.CODIGOMOVIMENTO, FO.CODIGODOTACAO,
  D.GRUPO, D.RECEITA, FO.DATA, FO.NEMPENHO, FO.DESCRICAO, FO.DEBITO, FO.CREDITO,
  FO.SALDO, FO.OBSERVACAO, D.DOTACAO
  FROM FICHAORCAMENTARIA FO
  INNER JOIN MOVIMENTO M ON (FO.CODIGOMOVIMENTO = M.CODIGO)
  INNER JOIN DOTACAO   D ON (FO.CODIGODOTACAO = D.CODIGO)
  WHERE FO.CODIGODOTACAO = :PCODIGODOTACAO
  AND FO.CODIGOMOVIMENTO = :PCODIGOMOVIMENTO AND (FO.DATA >= :PDATADE
  AND FO.DATA <= :PDATAATE)
  ORDER BY FO.DATA
  INTO :RCODIGO, :RCODIGOMOVIMENTO, :RCODIGODOTACAO, :RGRUPO, :RRECEITA, :RDATA,
  :RNEMPENHO, :RDESCRICAO, :RDEBITO, :RCREDITO, :RSALDO, :ROBSERVACAO,
  :RDESCRICAODOTACAO
  DO SUSPEND;
END
