CREATE PROCEDURE RELADESPESASMIUDASTOTAIS(
  PDESCRICAOCONTA VARCHAR(15) CHARACTER SET ISO8859_1,
  PDATADE DATE,
  PDATAATE DATE)
RETURNS(
  RDESCRICAOCONTA VARCHAR(150) CHARACTER SET ISO8859_1,
  RTDEBITO NUMERIC(18, 2),
  RNOMEAREA VARCHAR(40) CHARACTER SET ISO8859_1)
AS
BEGIN
  FOR SELECT SUM(L.DEBITO) AS TOTALDEBITO, C.DESCRICAO, A.NOME
  FROM LANCAMENTOS L
  INNER JOIN CONTAS      C ON (L.CODIGOCONTA = C.CODIGO)
  INNER JOIN TIPOSCONTAS T ON (C.CODIGOTIPOCONTA = T.CODIGO)
  INNER JOIN AREAS       A ON (C.CODIGOAREA = A.CODIGO)
  WHERE C.DESCRICAO = :PDESCRICAOCONTA AND L.DESCRICAO LIKE '%Despesas Mi%'
  AND (L.DATA >= :PDATADE AND L.DATA <= :PDATAATE)
  GROUP BY A.NOME, C.DESCRICAO
  ORDER BY A.NOME, C.DESCRICAO
  INTO :RTDEBITO, :RDESCRICAOCONTA, :RNOMEAREA
  DO SUSPEND;
END
