CREATE PROCEDURE RELADESPESASSUPLE(
  PCODIGOMOVIMENTO INTEGER,
  PCODIGOCONTA INTEGER)
RETURNS(
  RTDEBITO NUMERIC(18, 2),
  RTCREDITO NUMERIC(18, 2),
  RDESCRICAOCONTA VARCHAR(150) CHARACTER SET ISO8859_1)
AS
BEGIN
  FOR SELECT SUM(L.DEBITO) AS DEBITO, SUM(L.CREDITO), C.DESCRICAO
  FROM LANCAMENTOS L
  INNER JOIN CONTAS      C ON (L.CODIGOCONTA = C.CODIGO)
  INNER JOIN TIPOSCONTAS T ON (C.CODIGOTIPOCONTA = T.CODIGO)
  WHERE L.CODIGOMOVIMENTO = :PCODIGOMOVIMENTO AND C.CODIGO = :PCODIGOCONTA
  AND UPPER(L.DESCRICAO) LIKE '%' || 'SUPLEMENTA' || '%'
  GROUP BY C.DESCRICAO
  ORDER BY C.DESCRICAO
  INTO :RTDEBITO, :RTCREDITO, :RDESCRICAOCONTA
  DO SUSPEND;
END
