CREATE PROCEDURE RELADESPESASSDOAREA(
  PCODIGOMOVIMENTO INTEGER,
  PCODIGOAREA INTEGER)
RETURNS(
  RSALDO NUMERIC(18, 2),
  RNOME VARCHAR(150) CHARACTER SET ISO8859_1)
AS
BEGIN
  FOR SELECT SA.SALDOCONSUMO, A.NOME
  FROM AREAS A
  INNER JOIN SALDOAREAS SA ON (A.CODIGO = SA.CODIGOAREA)
  WHERE SA.CODIGOMOVIMENTO = :PCODIGOMOVIMENTO AND A.CODIGO = :PCODIGOAREA
  INTO :RSALDO, :RNOME
  DO SUSPEND;
END
