CREATE PROCEDURE RELASDOCONTAS(
  PCODIGOTIPOCONTA INTEGER,
  PCODIGOMOVIMENTO INTEGER)
RETURNS(
  RDESCRICAOCONTA VARCHAR(150) CHARACTER SET ISO8859_1,
  RDESCRICAOTIPOCONTA VARCHAR(150) CHARACTER SET ISO8859_1,
  RTOTALCREDITO NUMERIC(18, 2),
  RTOTALDEBITO NUMERIC(18, 2))
AS
BEGIN
  FOR SELECT C.DESCRICAO, T.DESCRICAO, (SUM(CREDITO)) AS TOTALCREDITO,
  (SUM(DEBITO)) AS TOTALDEBITO
  FROM CONTAS C
  INNER JOIN LANCAMENTOS L ON (C.CODIGO = L.CODIGOCONTA)
  INNER JOIN TIPOSCONTAS T ON (C.CODIGOTIPOCONTA = T.CODIGO)
  WHERE C.CODIGOTIPOCONTA = :PCODIGOTIPOCONTA AND L.RECEITA <> 'S' AND L.CODIGOMOVIMENTO = :PCODIGOMOVIMENTO
  GROUP BY C.DESCRICAO, T.DESCRICAO
  ORDER BY C.DESCRICAO, T.DESCRICAO
  INTO :RDESCRICAOCONTA, :RDESCRICAOTIPOCONTA, :RTOTALCREDITO, :RTOTALDEBITO
  DO SUSPEND;
END
