CREATE PROCEDURE RELABALANCETE(
  PCODIGOMOVIMENTO INTEGER,
  PCODIGOTIPOCONTA INTEGER,
  PDATA DATE)
RETURNS(
  RDESCRICAOTIPOCONTA VARCHAR(150) CHARACTER SET ISO8859_1,
  RDESCRICAOCONTA VARCHAR(150) CHARACTER SET ISO8859_1,
  RTOTALDEBITO NUMERIC(18, 2),
  RTOTALCREDITO NUMERIC(18, 2))
AS
BEGIN
  FOR SELECT T.DESCRICAO, C.DESCRICAO, (SUM(L.CREDITO)), (SUM(L.DEBITO))
  FROM TIPOSCONTAS T
  INNER JOIN CONTAS      C ON (T.CODIGO = C.CODIGOTIPOCONTA)
  INNER JOIN LANCAMENTOS L ON (C.CODIGO = L.CODIGOCONTA)
  WHERE L.CODIGOMOVIMENTO = :PCODIGOMOVIMENTO AND T.BALANCETE = 'S'
  AND C.CODIGOTIPOCONTA = :PCODIGOTIPOCONTA AND (L.DATA <= :PDATA)
  GROUP BY T.DESCRICAO, C.DESCRICAO
  ORDER BY T.DESCRICAO, C.DESCRICAO
  INTO :RDESCRICAOTIPOCONTA, :RDESCRICAOCONTA, :RTOTALCREDITO, :RTOTALDEBITO
  DO SUSPEND;
END
