CREATE PROCEDURE RELADESPESASMIUDAS(
  PCODIGOCONTA INTEGER,
  PDATADE DATE,
  PDATAATE DATE)
RETURNS(
  RCODIGO INTEGER,
  RCODIGOCONTA INTEGER,
  RDATA DATE,
  RDESCRICAO VARCHAR(150) CHARACTER SET ISO8859_1,
  RDEBITO NUMERIC(18, 2),
  RDESCRICAOCONTA VARCHAR(150) CHARACTER SET ISO8859_1,
  RNOMEAREA VARCHAR(40) CHARACTER SET ISO8859_1)
AS
BEGIN
  FOR SELECT L.CODIGO, L.CODIGOCONTA, L.DATA, L.DESCRICAO, L.DEBITO,
  C.DESCRICAO, A.NOME
  FROM LANCAMENTOS L
  INNER JOIN CONTAS      C ON (L.CODIGOCONTA = C.CODIGO)
  INNER JOIN TIPOSCONTAS T ON (C.CODIGOTIPOCONTA = T.CODIGO)
  INNER JOIN AREAS       A ON (C.CODIGOAREA = A.CODIGO)
  WHERE L.CODIGOCONTA = :PCODIGOCONTA AND L.DESCRICAO LIKE '%Despesas Mi%'
  AND (L.DATA >= :PDATADE
  AND L.DATA  <= :PDATAATE)
  GROUP BY L.CODIGO, L.CODIGOCONTA, L.DATA, L.DESCRICAO, L.DEBITO, C.DESCRICAO,
  A.NOME
  ORDER BY A.NOME, C.DESCRICAO, L.DATA
  INTO :RCODIGO, :RCODIGOCONTA, :RDATA, :RDESCRICAO, :RDEBITO, :RDESCRICAOCONTA,
  :RNOMEAREA
  DO SUSPEND;
END
