CREATE PROCEDURE RELALANCAMENTOS(
  PCODIGOCONTA INTEGER,
  PCODIGOMOVIMENTO INTEGER,
  PDATADE DATE,
  PDATAATE DATE)
RETURNS(
  RCODIGO INTEGER,
  RCODIGOMOVIMENTO INTEGER,
  RCODIGOORCAMENTO INTEGER,
  RCODIGOCONTA INTEGER,
  RGRUPO CHAR(6) CHARACTER SET ISO8859_1,
  RRECEITA CHAR(1) CHARACTER SET ISO8859_1,
  RDATA DATE,
  RNEMPENHO INTEGER,
  RDESCRICAO VARCHAR(150) CHARACTER SET ISO8859_1,
  RDEBITO NUMERIC(18, 2),
  RCREDITO NUMERIC(18, 2),
  RSALDO NUMERIC(18, 2),
  ROBSERVACAO VARCHAR(150) CHARACTER SET ISO8859_1,
  RDESCRICAOCONTA VARCHAR(150) CHARACTER SET ISO8859_1,
  RNOMEAREA VARCHAR(150) CHARACTER SET ISO8859_1,
  RDESCRICAOTIPOCONTA VARCHAR(150) CHARACTER SET ISO8859_1)
AS
BEGIN
  FOR SELECT L.CODIGO, L.CODIGOMOVIMENTO, L.CODIGOORCAMENTO, L.CODIGOCONTA,
  L.GRUPO, L.RECEITA, L.DATA, L.NEMPENHO, L.DESCRICAO, L.DEBITO, L.CREDITO,
  L.SALDO, L.OBSERVACAO, C.DESCRICAO, A.NOME, T.DESCRICAO
  FROM LANCAMENTOS L
  INNER JOIN MOVIMENTO   M ON (L.CODIGOMOVIMENTO = M.CODIGO)
  INNER JOIN CONTAS      C ON (L.CODIGOCONTA = C.CODIGO)
  LEFT  JOIN AREAS       A ON (C.CODIGOAREA = A.CODIGO)
  INNER JOIN TIPOSCONTAS T ON (C.CODIGOTIPOCONTA = T.CODIGO)
  WHERE L.CODIGOCONTA = :PCODIGOCONTA AND L.CODIGOMOVIMENTO = :PCODIGOMOVIMENTO
  AND (L.DATA >= :PDATADE AND L.DATA <= :PDATAATE)
  ORDER BY L.DATA
  INTO :RCODIGO, :RCODIGOMOVIMENTO, :RCODIGOORCAMENTO, :RCODIGOCONTA, :RGRUPO,
  :RRECEITA, :RDATA, :RNEMPENHO, :RDESCRICAO, :RDEBITO, :RCREDITO, :RSALDO,
  :ROBSERVACAO, :RDESCRICAOCONTA, :RNOMEAREA, :RDESCRICAOTIPOCONTA
  DO SUSPEND;
END
