CREATE PROCEDURE RELAGASTONAOSUPLEMENTACAO(
  PCODIGOMOVIMENTO INTEGER,
  PGRUPO CHAR(6) CHARACTER SET ISO8859_1,
  PRECEITA CHAR(1) CHARACTER SET ISO8859_1)
RETURNS(
  RDESCRICAO VARCHAR(150) CHARACTER SET ISO8859_1,
  RTOTALCREDITO NUMERIC(18, 2),
  RTOTALDEBITO NUMERIC(18, 2))
AS
BEGIN
  FOR SELECT C.DESCRICAO, (SUM(L.CREDITO)) AS TOTALCREDITO,
  (SUM(L.DEBITO)) AS TOTALDEBITO
  FROM LANCAMENTOS L
  INNER JOIN CONTAS            C  ON (L.CODIGOCONTA = C.CODIGO)
  INNER JOIN TIPOSCONTAS       T  ON (C.CODIGOTIPOCONTA = T.CODIGO)
  INNER JOIN FICHAORCAMENTARIA FO ON (L.CODIGOORCAMENTO = FO.CODIGO)
  INNER JOIN DOTACAO           D  ON (FO.CODIGODOTACAO = D.CODIGO)
  WHERE FO.CODIGOMOVIMENTO = :PCODIGOMOVIMENTO
  AND UPPER(L.DESCRICAO) NOT LIKE '%SUPLEMENTA%'
  AND UPPER(D.RECEITA) = UPPER(:PRECEITA) AND D.GRUPO = :PGRUPO
  AND UPPER(T.DESCRICAO) LIKE 'GASTO%'
  GROUP BY C.DESCRICAO
  ORDER BY C.DESCRICAO
  INTO :RDESCRICAO, :RTOTALCREDITO, :RTOTALDEBITO
  DO SUSPEND;
END
