CREATE PROCEDURE RELADESPESASSDOTAREA(
  PCODIGOMOVIMENTO INTEGER)
RETURNS(
  RNOME VARCHAR(150) CHARACTER SET ISO8859_1,
  RSALDOCONSUMO NUMERIC(18, 2),
  RTDEBITO NUMERIC(18, 2),
  RTCREDITO NUMERIC(18, 2),
  RUSUARIO VARCHAR(10) CHARACTER SET ISO8859_1,
  RDHMODIFICACAO TIMESTAMP)
AS
BEGIN
  FOR SELECT A.NOME, SA.SALDOCONSUMO, SUM(L.DEBITO), SUM(L.CREDITO), SA.USUARIO,
  SA.DHMODIFICACAO
  FROM SALDOAREAS SA
  LEFT JOIN AREAS       A ON (SA.CODIGOAREA = A.CODIGO)
  LEFT JOIN CONTAS      C ON (A.CODIGO = C.CODIGOAREA)
  LEFT JOIN LANCAMENTOS L ON (C.CODIGO = L.CODIGOCONTA)
  WHERE (L.DESCRICAO LIKE '%' || 'Almoxarifado' || '%'
  OR L.DESCRICAO LIKE '%' || 'Miúdas' || '%')
  AND SA.CODIGOMOVIMENTO = :PCODIGOMOVIMENTO
  AND L.CODIGOMOVIMENTO = :PCODIGOMOVIMENTO
  GROUP BY A.NOME, SA.SALDOCONSUMO, SA.USUARIO, SA.DHMODIFICACAO
  ORDER BY A.NOME, SA.SALDOCONSUMO
  INTO :RNOME, :RSALDOCONSUMO, :RTDEBITO, :RTCREDITO, :RUSUARIO, :RDHMODIFICACAO
  DO SUSPEND;
END
