CREATE PROCEDURE RELAFICHAORCAMENTSDOINICIAL(
  PCODIGOMOVIMENTO INTEGER,
  PGRUPO CHAR(6) CHARACTER SET ISO8859_1,
  PRECEITA CHAR(1) CHARACTER SET ISO8859_1)
RETURNS(
  RDESCRICAOGRUPO VARCHAR(150) CHARACTER SET ISO8859_1,
  RSALDOINICIAL NUMERIC(18, 2))
AS
BEGIN
  FOR SELECT D.DESCRICAOGRUPO, (SUM(F.CREDITO)) AS SDOINICIAL
  FROM DOTACAO D
  INNER JOIN FICHAORCAMENTARIA F ON (D.CODIGO = F.CODIGODOTACAO)
  WHERE F.CODIGOMOVIMENTO = :PCODIGOMOVIMENTO
  AND UPPER(F.DESCRICAO) LIKE 'SALDO INICIAL%' AND D.GRUPO LIKE :PGRUPO
  AND UPPER(D.RECEITA) = UPPER(:PRECEITA)
  GROUP BY DESCRICAOGRUPO
  INTO :RDESCRICAOGRUPO, :RSALDOINICIAL
  DO SUSPEND;
END
