INSERT INTO TIPOSCONTAS (CODIGO, DESCRICAO, FICHAORCAMENTARIA, BALANCETE, USUARIO, DHMODIFICACAO)
VALUES 
  (4, 'ORÇAMENTO', 'S', 'S', 'S3011130', '2006-06-08 10:06:47');

INSERT INTO TIPOSCONTAS (CODIGO, DESCRICAO, FICHAORCAMENTARIA, BALANCETE, USUARIO, DHMODIFICACAO)
VALUES 
  (5, 'RENDA INDUSTRIAL', 'S', 'S', 'S3011130', '2006-06-08 10:06:37');

INSERT INTO TIPOSCONTAS (CODIGO, DESCRICAO, FICHAORCAMENTARIA, BALANCETE, USUARIO, DHMODIFICACAO)
VALUES 
  (7, 'AREAS/SEÇÕES', 'S', '', 'RETOMA', '2008-02-14 06:50:37');

INSERT INTO TIPOSCONTAS (CODIGO, DESCRICAO, FICHAORCAMENTARIA, BALANCETE, USUARIO, DHMODIFICACAO)
VALUES 
  (8, 'PREVISÃO DA ADMINISTRAÇÃO', 'S', 'N', 'SYSDBA', '2008-01-03 16:32:01');

INSERT INTO TIPOSCONTAS (CODIGO, DESCRICAO, FICHAORCAMENTARIA, BALANCETE, USUARIO, DHMODIFICACAO)
VALUES 
  (10, 'GASTO EFETIVO', 'S', '', 'NUNO', '2018-02-09 10:41:24');

INSERT INTO TIPOSCONTAS (CODIGO, DESCRICAO, FICHAORCAMENTARIA, BALANCETE, USUARIO, DHMODIFICACAO)
VALUES 
  (11, 'PROJETOS ESPECIAIS', 'S', 'N', 'SYSDBA', '2008-01-03 16:32:00');

INSERT INTO TIPOSCONTAS (CODIGO, DESCRICAO, FICHAORCAMENTARIA, BALANCETE, USUARIO, DHMODIFICACAO)
VALUES 
  (20, 'ADMINISTRAÇÃO', 'N', 'N', 'SYSDBA', '2008-01-03 16:31:59');

INSERT INTO TIPOSCONTAS (CODIGO, DESCRICAO, FICHAORCAMENTARIA, BALANCETE, USUARIO, DHMODIFICACAO)
VALUES 
  (21, 'CURSO DE GRADUAÇÃO', 'N', 'N', 'SYSDBA', '2008-01-03 16:31:59');

INSERT INTO TIPOSCONTAS (CODIGO, DESCRICAO, FICHAORCAMENTARIA, BALANCETE, USUARIO, DHMODIFICACAO)
VALUES 
  (24, 'FICHA ORÇAMENTÁRIA', 'N', 'N', 'SYSDBA', '2008-01-03 16:31:57');

INSERT INTO TIPOSCONTAS (CODIGO, DESCRICAO, FICHAORCAMENTARIA, BALANCETE, USUARIO, DHMODIFICACAO)
VALUES 
  (25, 'RESERVA', 'S', 'N', 'SYSDBA', '2008-01-03 16:31:56');

INSERT INTO TIPOSCONTAS (CODIGO, DESCRICAO, FICHAORCAMENTARIA, BALANCETE, USUARIO, DHMODIFICACAO)
VALUES 
  (26, 'AREAS/ALMOXARIFADO', 'N', 'N', 'SYSDBA', '2008-01-03 16:31:55');

INSERT INTO TIPOSCONTAS (CODIGO, DESCRICAO, FICHAORCAMENTARIA, BALANCETE, USUARIO, DHMODIFICACAO)
VALUES 
  (27, 'MANUTENÇÃO PREDIAL - 081', 'N', 'N', 'SYSDBA', '2008-01-03 16:31:55');

INSERT INTO TIPOSCONTAS (CODIGO, DESCRICAO, FICHAORCAMENTARIA, BALANCETE, USUARIO, DHMODIFICACAO)
VALUES 
  (28, 'SEGURANÇA E PROTEÇÃO - 082', 'N', 'N', 'SYSDBA', '2008-01-03 16:31:54');

INSERT INTO TIPOSCONTAS (CODIGO, DESCRICAO, FICHAORCAMENTARIA, BALANCETE, USUARIO, DHMODIFICACAO)
VALUES 
  (29, 'INFORMÁTICA - 083', 'N', 'N', 'SYSDBA', '2008-01-03 16:31:53');

INSERT INTO TIPOSCONTAS (CODIGO, DESCRICAO, FICHAORCAMENTARIA, BALANCETE, USUARIO, DHMODIFICACAO)
VALUES 
  (30, 'TREINAMENTO E CURSOS - 084', 'N', 'N', 'SYSDBA', '2008-01-03 16:31:53');

INSERT INTO TIPOSCONTAS (CODIGO, DESCRICAO, FICHAORCAMENTARIA, BALANCETE, USUARIO, DHMODIFICACAO)
VALUES 
  (31, 'SERVIÇO DIAGRAMAÇÃO E DIGITALIZAÇÃO - ADM', 'N', 'N', 'SYSDBA', '2008-01-03 16:31:52');

INSERT INTO TIPOSCONTAS (CODIGO, DESCRICAO, FICHAORCAMENTARIA, BALANCETE, USUARIO, DHMODIFICACAO)
VALUES 
  (32, 'DESPESAS COM VERBA RI PAGA NA BASICA', 'N', 'N', 'SYSDBA', '2008-01-03 16:31:52');

INSERT INTO TIPOSCONTAS (CODIGO, DESCRICAO, FICHAORCAMENTARIA, BALANCETE, USUARIO, DHMODIFICACAO)
VALUES 
  (33, 'DESPESAS COM VERBA DA BASICA PAGA NA RI', 'N', 'N', 'SYSDBA', '2008-01-03 16:31:51');

INSERT INTO TIPOSCONTAS (CODIGO, DESCRICAO, FICHAORCAMENTARIA, BALANCETE, USUARIO, DHMODIFICACAO)
VALUES 
  (34, 'RENDA INDUSTRIAL - ADMINISTRAÇÃO', 'S', 'N', 'SYSDBA', '2008-01-03 16:31:50');

INSERT INTO TIPOSCONTAS (CODIGO, DESCRICAO, FICHAORCAMENTARIA, BALANCETE, USUARIO, DHMODIFICACAO)
VALUES 
  (35, 'DOAÇÃO', 'S', 'N', 'SYSDBA', '2008-01-03 16:32:12');

INSERT INTO TIPOSCONTAS (CODIGO, DESCRICAO, FICHAORCAMENTARIA, BALANCETE, USUARIO, DHMODIFICACAO)
VALUES 
  (36, 'PROAP', 'S', 'N', 'SYSDBA', '2008-01-03 16:32:13');

INSERT INTO TIPOSCONTAS (CODIGO, DESCRICAO, FICHAORCAMENTARIA, BALANCETE, USUARIO, DHMODIFICACAO)
VALUES 
  (37, 'MONITORES BOLSISTAS', '', '', 'RETOMA', '2008-01-28 06:49:32');

INSERT INTO TIPOSCONTAS (CODIGO, DESCRICAO, FICHAORCAMENTARIA, BALANCETE, USUARIO, DHMODIFICACAO)
VALUES 
  (38, 'FUNDO DE PUBLICAÇÃO', 'S', '', 'RETOMA', '2008-01-28 08:53:44');

INSERT INTO TIPOSCONTAS (CODIGO, DESCRICAO, FICHAORCAMENTARIA, BALANCETE, USUARIO, DHMODIFICACAO)
VALUES 
  (40, 'CONVÊNIO PROAP', '', '', 'RETOMA', '2010-09-15 12:05:21');

INSERT INTO TIPOSCONTAS (CODIGO, DESCRICAO, FICHAORCAMENTARIA, BALANCETE, USUARIO, DHMODIFICACAO)
VALUES 
  (41, 'CONVÊNIO PROEX', '', '', 'RETOMA', '2010-09-15 12:05:34');

INSERT INTO TIPOSCONTAS (CODIGO, DESCRICAO, FICHAORCAMENTARIA, BALANCETE, USUARIO, DHMODIFICACAO)
VALUES 
  (42, 'PASSAGEM AÉREA', '', '', 'RETOMA', '2011-09-19 10:54:36');

INSERT INTO TIPOSCONTAS (CODIGO, DESCRICAO, FICHAORCAMENTARIA, BALANCETE, USUARIO, DHMODIFICACAO)
VALUES 
  (43, 'REEMBOLSO PASSAGEM AÉREA ECCOS', '', '', 'RETOMA', '2012-12-12 10:57:08');

INSERT INTO TIPOSCONTAS (CODIGO, DESCRICAO, FICHAORCAMENTARIA, BALANCETE, USUARIO, DHMODIFICACAO)
VALUES 
  (44, 'PAGAMENTO PASSAGEM AÉREA VERBA CONVÊNIO', '', '', 'RETOMA', '2012-12-19 15:51:43');

INSERT INTO TIPOSCONTAS (CODIGO, DESCRICAO, FICHAORCAMENTARIA, BALANCETE, USUARIO, DHMODIFICACAO)
VALUES 
  (45, 'PROGRAMAS - CONVÊNIOS - GRUPO 801', 'S', '', 'RETOMA', '2018-03-27 16:03:14');

INSERT INTO TIPOSCONTAS (CODIGO, DESCRICAO, FICHAORCAMENTARIA, BALANCETE, USUARIO, DHMODIFICACAO)
VALUES 
  (46, 'PREVISÃO - CONVÊNIOS - GRUPO 179', 'S', '', 'NUNO', '2015-09-29 09:41:41');

INSERT INTO TIPOSCONTAS (CODIGO, DESCRICAO, FICHAORCAMENTARIA, BALANCETE, USUARIO, DHMODIFICACAO)
VALUES 
  (47, 'PROGRAMAS CPG', 'S', '', 'NUNO', '2015-10-05 10:38:16');

INSERT INTO TIPOSCONTAS (CODIGO, DESCRICAO, FICHAORCAMENTARIA, BALANCETE, USUARIO, DHMODIFICACAO)
VALUES 
  (48, 'DESENVTO. PROGRS. INTERNACIONALIZAÇÃO - CPG - R.I.', 'S', '', 'NUNO', '2018-03-12 10:54:52');

INSERT INTO TIPOSCONTAS (CODIGO, DESCRICAO, FICHAORCAMENTARIA, BALANCETE, USUARIO, DHMODIFICACAO)
VALUES 
  (49, 'PROGRAMAS APOIO PUBLICAÇÕES - CPG - R.I.', 'S', '', 'NUNO', '2018-03-12 14:52:31');

INSERT INTO TIPOSCONTAS (CODIGO, DESCRICAO, FICHAORCAMENTARIA, BALANCETE, USUARIO, DHMODIFICACAO)
VALUES 
  (50, 'PROGRAMAS - CONVÊNIOS - CAPES - 40074', 'S', '', 'NUNO', '2017-08-25 15:27:06');

COMMIT WORK;

